### PR TITLE
Removed vulkan-1.lib

### PR DESCRIPTION
**Pull request by georged-youi**

### CODE REVIEW

**Review by mathieumallet — APPROVED** [review]

**Comment by gadzooka** [comment]
Is there a jira?

**Comment by georged-youi** [comment]
> 



> Is there a jira?

it's part of YPE-2671

**Comment by mathieumallet** [comment]
too late now but I think what chris meant was 'should there be a jira number in the commit title'

**Comment by georged-youi** [comment]
> too late now but I think what chris meant was 'should there be a jira number in the commit title'

all the commits in this repo don't have jira numbers attached to them. just following the trend.

**Pull request merged**
